defmodule HPack.Huffman do
  @moduledoc """
    Huffman static table de/encoding as defined in RFC 7541.
  """

  @doc """
    Decodes a Huffman encoded string with the HPACK static table.

    Returns the decoded String.

    ## Examples

      iex> HPack.Huffman.decode(<< 0x27::6, 0x5::5, 0x28::6, 0x28::6, 0x7::5 >>)
      "hello"

  """
  @spec decode(String.t) :: String.t
  def decode(encoded) do
    dec(encoded, bit_size(encoded), <<>>)
  end

  # eos
  defp dec(rest, 0, string), do: string
  defp dec(<< 0b1::1 >>, 1, string), do: string
  defp dec(<< 0b11::2 >>, 2, string), do: string
  defp dec(<< 0b111::3 >>, 3, string), do: string
  defp dec(<< 0b1111::4 >>, 4, string), do: string
  defp dec(<< 0b11111::5 >>, 5, string), do: string
  defp dec(<< 0b111111::6 >>, 6, string), do: string
  defp dec(<< 0b1111111::7 >>, 7, string), do: string

  # static huffman table
  defp dec(<< 0x7ffffe7::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<244>>)
  defp dec(<< 0x7ffffe8::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<245>>)
  defp dec(<< 0x7ffffe9::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<246>>)
  defp dec(<< 0x7ffffea::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<247>>)
  defp dec(<< 0x7ffffeb::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<248>>)
  defp dec(<< 0xffffffe::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<249>>)
  defp dec(<< 0x7ffffec::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<250>>)
  defp dec(<< 0x7ffffed::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<251>>)
  defp dec(<< 0x7ffffee::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<252>>)
  defp dec(<< 0x7ffffef::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<253>>)
  defp dec(<< 0x7fffff0::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<254>>)
  defp dec(<< 0x3ffffee::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<255>>)
  defp dec(<< 0x3fffffff::30, rest::bitstring >>, length, result), do: dec(rest, length - 30, result <> <<256>>)
  defp dec(<< 0x1ffffed::25, rest::bitstring >>, length, result), do: dec(rest, length - 25, result <> <<207>>)
  defp dec(<< 0x7fff2::19, rest::bitstring >>, length, result), do: dec(rest, length - 19, result <> <<208>>)
  defp dec(<< 0x1fffe3::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<209>>)
  defp dec(<< 0x3ffffe6::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<210>>)
  defp dec(<< 0x7ffffe0::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<211>>)
  defp dec(<< 0x7ffffe1::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<212>>)
  defp dec(<< 0x3ffffe7::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<213>>)
  defp dec(<< 0x7ffffe2::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<214>>)
  defp dec(<< 0xfffff2::24, rest::bitstring >>, length, result), do: dec(rest, length - 24, result <> <<215>>)
  defp dec(<< 0x1fffe4::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<216>>)
  defp dec(<< 0x1fffe5::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<217>>)
  defp dec(<< 0x3ffffe8::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<218>>)
  defp dec(<< 0x3ffffe9::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<219>>)
  defp dec(<< 0xffffffd::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<220>>)
  defp dec(<< 0x7ffffe3::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<221>>)
  defp dec(<< 0x7ffffe4::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<222>>)
  defp dec(<< 0x7ffffe5::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<223>>)
  defp dec(<< 0xfffec::20, rest::bitstring >>, length, result), do: dec(rest, length - 20, result <> <<224>>)
  defp dec(<< 0xfffff3::24, rest::bitstring >>, length, result), do: dec(rest, length - 24, result <> <<225>>)
  defp dec(<< 0xfffed::20, rest::bitstring >>, length, result), do: dec(rest, length - 20, result <> <<226>>)
  defp dec(<< 0x1fffe6::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<227>>)
  defp dec(<< 0x3fffe9::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<228>>)
  defp dec(<< 0x1fffe7::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<229>>)
  defp dec(<< 0x1fffe8::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<230>>)
  defp dec(<< 0x7ffff3::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<231>>)
  defp dec(<< 0x3fffea::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<232>>)
  defp dec(<< 0x3fffeb::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<233>>)
  defp dec(<< 0x1ffffee::25, rest::bitstring >>, length, result), do: dec(rest, length - 25, result <> <<234>>)
  defp dec(<< 0x1ffffef::25, rest::bitstring >>, length, result), do: dec(rest, length - 25, result <> <<235>>)
  defp dec(<< 0xfffff4::24, rest::bitstring >>, length, result), do: dec(rest, length - 24, result <> <<236>>)
  defp dec(<< 0xfffff5::24, rest::bitstring >>, length, result), do: dec(rest, length - 24, result <> <<237>>)
  defp dec(<< 0x3ffffea::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<238>>)
  defp dec(<< 0x7ffff4::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<239>>)
  defp dec(<< 0x3ffffeb::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<240>>)
  defp dec(<< 0x7ffffe6::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<241>>)
  defp dec(<< 0x3ffffec::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<242>>)
  defp dec(<< 0x3ffffed::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<243>>)
  defp dec(<< 0x7ffffe7::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<244>>)
  defp dec(<< 0x7ffffe8::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<245>>)
  defp dec(<< 0x7ffffe9::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<246>>)
  defp dec(<< 0x7ffffea::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<247>>)
  defp dec(<< 0x7ffffeb::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<248>>)
  defp dec(<< 0xffffffe::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<249>>)
  defp dec(<< 0x7ffffec::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<250>>)
  defp dec(<< 0x7ffffed::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<251>>)
  defp dec(<< 0x7ffffee::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<252>>)
  defp dec(<< 0x7ffffef::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<253>>)
  defp dec(<< 0x7fffff0::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<254>>)
  defp dec(<< 0x3ffffee::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<255>>)
  defp dec(<< 0x3fffffff::30, rest::bitstring >>, length, result), do: dec(rest, length - 30, result <> <<256>>)
  defp dec(<< 0x2d::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<117>>)
  defp dec(<< 0x77::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<118>>)
  defp dec(<< 0x78::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<119>>)
  defp dec(<< 0x79::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<120>>)
  defp dec(<< 0x7a::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<121>>)
  defp dec(<< 0x7b::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<122>>)
  defp dec(<< 0x7ffe::15, rest::bitstring >>, length, result), do: dec(rest, length - 15, result <> <<123>>)
  defp dec(<< 0x7fc::11, rest::bitstring >>, length, result), do: dec(rest, length - 11, result <> <<124>>)
  defp dec(<< 0x3ffd::14, rest::bitstring >>, length, result), do: dec(rest, length - 14, result <> <<125>>)
  defp dec(<< 0x1ffd::13, rest::bitstring >>, length, result), do: dec(rest, length - 13, result <> <<126>>)
  defp dec(<< 0xffffffc::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<127>>)
  defp dec(<< 0xfffe6::20, rest::bitstring >>, length, result), do: dec(rest, length - 20, result <> <<128>>)
  defp dec(<< 0x3fffd2::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<129>>)
  defp dec(<< 0xfffe7::20, rest::bitstring >>, length, result), do: dec(rest, length - 20, result <> <<130>>)
  defp dec(<< 0xfffe8::20, rest::bitstring >>, length, result), do: dec(rest, length - 20, result <> <<131>>)
  defp dec(<< 0x3fffd3::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<132>>)
  defp dec(<< 0x3fffd4::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<133>>)
  defp dec(<< 0x3fffd5::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<134>>)
  defp dec(<< 0x7fffd9::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<135>>)
  defp dec(<< 0x3fffd6::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<136>>)
  defp dec(<< 0x7fffda::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<137>>)
  defp dec(<< 0x7fffdb::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<138>>)
  defp dec(<< 0x7fffdc::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<139>>)
  defp dec(<< 0x7fffdd::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<140>>)
  defp dec(<< 0x7fffde::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<141>>)
  defp dec(<< 0xffffeb::24, rest::bitstring >>, length, result), do: dec(rest, length - 24, result <> <<142>>)
  defp dec(<< 0x7fffdf::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<143>>)
  defp dec(<< 0xffffec::24, rest::bitstring >>, length, result), do: dec(rest, length - 24, result <> <<144>>)
  defp dec(<< 0xffffed::24, rest::bitstring >>, length, result), do: dec(rest, length - 24, result <> <<145>>)
  defp dec(<< 0x3fffd7::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<146>>)
  defp dec(<< 0x7fffe0::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<147>>)
  defp dec(<< 0xffffee::24, rest::bitstring >>, length, result), do: dec(rest, length - 24, result <> <<148>>)
  defp dec(<< 0x7fffe1::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<149>>)
  defp dec(<< 0x7fffe2::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<150>>)
  defp dec(<< 0x7fffe3::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<151>>)
  defp dec(<< 0x7fffe4::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<152>>)
  defp dec(<< 0x1fffdc::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<153>>)
  defp dec(<< 0x3fffd8::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<154>>)
  defp dec(<< 0x7fffe5::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<155>>)
  defp dec(<< 0x3fffd9::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<156>>)
  defp dec(<< 0x7fffe6::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<157>>)
  defp dec(<< 0x7fffe7::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<158>>)
  defp dec(<< 0xffffef::24, rest::bitstring >>, length, result), do: dec(rest, length - 24, result <> <<159>>)
  defp dec(<< 0x3fffda::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<160>>)
  defp dec(<< 0x1fffdd::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<161>>)
  defp dec(<< 0xfffe9::20, rest::bitstring >>, length, result), do: dec(rest, length - 20, result <> <<162>>)
  defp dec(<< 0x3fffdb::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<163>>)
  defp dec(<< 0x3fffdc::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<164>>)
  defp dec(<< 0x7fffe8::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<165>>)
  defp dec(<< 0x7fffe9::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<166>>)
  defp dec(<< 0x1fffde::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<167>>)
  defp dec(<< 0x7fffea::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<168>>)
  defp dec(<< 0x3fffdd::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<169>>)
  defp dec(<< 0x3fffde::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<170>>)
  defp dec(<< 0xfffff0::24, rest::bitstring >>, length, result), do: dec(rest, length - 24, result <> <<171>>)
  defp dec(<< 0x1fffdf::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<172>>)
  defp dec(<< 0x3fffdf::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<173>>)
  defp dec(<< 0x7fffeb::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<174>>)
  defp dec(<< 0x7fffec::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<175>>)
  defp dec(<< 0x1fffe0::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<176>>)
  defp dec(<< 0x1fffe1::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<177>>)
  defp dec(<< 0x3fffe0::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<178>>)
  defp dec(<< 0x1fffe2::21, rest::bitstring >>, length, result), do: dec(rest, length - 21, result <> <<179>>)
  defp dec(<< 0x7fffed::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<180>>)
  defp dec(<< 0x3fffe1::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<181>>)
  defp dec(<< 0x7fffee::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<182>>)
  defp dec(<< 0x7fffef::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<183>>)
  defp dec(<< 0xfffea::20, rest::bitstring >>, length, result), do: dec(rest, length - 20, result <> <<184>>)
  defp dec(<< 0x3fffe2::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<185>>)
  defp dec(<< 0x3fffe3::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<186>>)
  defp dec(<< 0x3fffe4::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<187>>)
  defp dec(<< 0x7ffff0::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<188>>)
  defp dec(<< 0x3fffe5::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<189>>)
  defp dec(<< 0x3fffe6::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<190>>)
  defp dec(<< 0x7ffff1::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<191>>)
  defp dec(<< 0x3ffffe0::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<192>>)
  defp dec(<< 0x3ffffe1::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<193>>)
  defp dec(<< 0xfffeb::20, rest::bitstring >>, length, result), do: dec(rest, length - 20, result <> <<194>>)
  defp dec(<< 0x7fff1::19, rest::bitstring >>, length, result), do: dec(rest, length - 19, result <> <<195>>)
  defp dec(<< 0x3fffe7::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<196>>)
  defp dec(<< 0x7ffff2::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<197>>)
  defp dec(<< 0x3fffe8::22, rest::bitstring >>, length, result), do: dec(rest, length - 22, result <> <<198>>)
  defp dec(<< 0x1ffffec::25, rest::bitstring >>, length, result), do: dec(rest, length - 25, result <> <<199>>)
  defp dec(<< 0x3ffffe2::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<200>>)
  defp dec(<< 0x3ffffe3::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<201>>)
  defp dec(<< 0x3ffffe4::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<202>>)
  defp dec(<< 0x7ffffde::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<203>>)
  defp dec(<< 0x7ffffdf::27, rest::bitstring >>, length, result), do: dec(rest, length - 27, result <> <<204>>)
  defp dec(<< 0x3ffffe5::26, rest::bitstring >>, length, result), do: dec(rest, length - 26, result <> <<205>>)
  defp dec(<< 0xfffff1::24, rest::bitstring >>, length, result), do: dec(rest, length - 24, result <> <<206>>)
  defp dec(<< 0x1::5, rest::bitstring >>, length, result), do: dec(rest, length - 5, result <> <<49>>)
  defp dec(<< 0x2::5, rest::bitstring >>, length, result), do: dec(rest, length - 5, result <> <<50>>)
  defp dec(<< 0x19::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<51>>)
  defp dec(<< 0x1a::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<52>>)
  defp dec(<< 0x1b::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<53>>)
  defp dec(<< 0x1c::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<54>>)
  defp dec(<< 0x1d::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<55>>)
  defp dec(<< 0x1e::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<56>>)
  defp dec(<< 0x1f::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<57>>)
  defp dec(<< 0x5c::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<58>>)
  defp dec(<< 0xfb::8, rest::bitstring >>, length, result), do: dec(rest, length - 8, result <> <<59>>)
  defp dec(<< 0x7ffc::15, rest::bitstring >>, length, result), do: dec(rest, length - 15, result <> <<60>>)
  defp dec(<< 0x20::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<61>>)
  defp dec(<< 0xffb::12, rest::bitstring >>, length, result), do: dec(rest, length - 12, result <> <<62>>)
  defp dec(<< 0x3fc::10, rest::bitstring >>, length, result), do: dec(rest, length - 10, result <> <<63>>)
  defp dec(<< 0x1ffa::13, rest::bitstring >>, length, result), do: dec(rest, length - 13, result <> <<64>>)
  defp dec(<< 0x21::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<65>>)
  defp dec(<< 0x5d::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<66>>)
  defp dec(<< 0x5e::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<67>>)
  defp dec(<< 0x5f::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<68>>)
  defp dec(<< 0x60::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<69>>)
  defp dec(<< 0x61::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<70>>)
  defp dec(<< 0x62::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<71>>)
  defp dec(<< 0x63::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<72>>)
  defp dec(<< 0x64::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<73>>)
  defp dec(<< 0x65::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<74>>)
  defp dec(<< 0x66::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<75>>)
  defp dec(<< 0x67::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<76>>)
  defp dec(<< 0x68::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<77>>)
  defp dec(<< 0x69::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<78>>)
  defp dec(<< 0x6a::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<79>>)
  defp dec(<< 0x6b::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<80>>)
  defp dec(<< 0x6c::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<81>>)
  defp dec(<< 0x6d::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<82>>)
  defp dec(<< 0x6e::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<83>>)
  defp dec(<< 0x6f::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<84>>)
  defp dec(<< 0x70::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<85>>)
  defp dec(<< 0x71::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<86>>)
  defp dec(<< 0x72::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<87>>)
  defp dec(<< 0xfc::8, rest::bitstring >>, length, result), do: dec(rest, length - 8, result <> <<88>>)
  defp dec(<< 0x73::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<89>>)
  defp dec(<< 0xfd::8, rest::bitstring >>, length, result), do: dec(rest, length - 8, result <> <<90>>)
  defp dec(<< 0x1ffb::13, rest::bitstring >>, length, result), do: dec(rest, length - 13, result <> <<91>>)
  defp dec(<< 0x7fff0::19, rest::bitstring >>, length, result), do: dec(rest, length - 19, result <> <<92>>)
  defp dec(<< 0x1ffc::13, rest::bitstring >>, length, result), do: dec(rest, length - 13, result <> <<93>>)
  defp dec(<< 0x3ffc::14, rest::bitstring >>, length, result), do: dec(rest, length - 14, result <> <<94>>)
  defp dec(<< 0x22::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<95>>)
  defp dec(<< 0x7ffd::15, rest::bitstring >>, length, result), do: dec(rest, length - 15, result <> <<96>>)
  defp dec(<< 0x3::5, rest::bitstring >>, length, result), do: dec(rest, length - 5, result <> <<97>>)
  defp dec(<< 0x23::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<98>>)
  defp dec(<< 0x4::5, rest::bitstring >>, length, result), do: dec(rest, length - 5, result <> <<99>>)
  defp dec(<< 0x24::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<100>>)
  defp dec(<< 0x5::5, rest::bitstring >>, length, result), do: dec(rest, length - 5, result <> <<101>>)
  defp dec(<< 0x25::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<102>>)
  defp dec(<< 0x26::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<103>>)
  defp dec(<< 0x27::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<104>>)
  defp dec(<< 0x6::5, rest::bitstring >>, length, result), do: dec(rest, length - 5, result <> <<105>>)
  defp dec(<< 0x74::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<106>>)
  defp dec(<< 0x75::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<107>>)
  defp dec(<< 0x28::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<108>>)
  defp dec(<< 0x29::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<109>>)
  defp dec(<< 0x2a::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<110>>)
  defp dec(<< 0x7::5, rest::bitstring >>, length, result), do: dec(rest, length - 5, result <> <<111>>)
  defp dec(<< 0x2b::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<112>>)
  defp dec(<< 0x76::7, rest::bitstring >>, length, result), do: dec(rest, length - 7, result <> <<113>>)
  defp dec(<< 0x2c::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<114>>)
  defp dec(<< 0x8::5, rest::bitstring >>, length, result), do: dec(rest, length - 5, result <> <<115>>)
  defp dec(<< 0x9::5, rest::bitstring >>, length, result), do: dec(rest, length - 5, result <> <<116>>)
  defp dec(<< 0x1ff8::13, rest::bitstring >>, length, result), do: dec(rest, length - 13, result <> <<0>>)
  defp dec(<< 0x7fffd8::23, rest::bitstring >>, length, result), do: dec(rest, length - 23, result <> <<1>>)
  defp dec(<< 0xfffffe2::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<2>>)
  defp dec(<< 0xfffffe3::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<3>>)
  defp dec(<< 0xfffffe4::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<4>>)
  defp dec(<< 0xfffffe5::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<5>>)
  defp dec(<< 0xfffffe6::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<6>>)
  defp dec(<< 0xfffffe7::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<7>>)
  defp dec(<< 0xfffffe8::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<8>>)
  defp dec(<< 0xffffea::24, rest::bitstring >>, length, result), do: dec(rest, length - 24, result <> <<9>>)
  defp dec(<< 0x3ffffffc::30, rest::bitstring >>, length, result), do: dec(rest, length - 30, result <> <<10>>)
  defp dec(<< 0xfffffe9::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<11>>)
  defp dec(<< 0xfffffea::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<12>>)
  defp dec(<< 0x3ffffffd::30, rest::bitstring >>, length, result), do: dec(rest, length - 30, result <> <<13>>)
  defp dec(<< 0xfffffeb::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<14>>)
  defp dec(<< 0xfffffec::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<15>>)
  defp dec(<< 0xfffffed::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<16>>)
  defp dec(<< 0xfffffee::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<17>>)
  defp dec(<< 0xfffffef::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<18>>)
  defp dec(<< 0xffffff0::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<19>>)
  defp dec(<< 0xffffff1::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<20>>)
  defp dec(<< 0xffffff2::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<21>>)
  defp dec(<< 0x3ffffffe::30, rest::bitstring >>, length, result), do: dec(rest, length - 30, result <> <<22>>)
  defp dec(<< 0xffffff3::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<23>>)
  defp dec(<< 0xffffff4::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<24>>)
  defp dec(<< 0xffffff5::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<25>>)
  defp dec(<< 0xffffff6::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<26>>)
  defp dec(<< 0xffffff7::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<27>>)
  defp dec(<< 0xffffff8::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<28>>)
  defp dec(<< 0xffffff9::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<29>>)
  defp dec(<< 0xffffffa::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<30>>)
  defp dec(<< 0xffffffb::28, rest::bitstring >>, length, result), do: dec(rest, length - 28, result <> <<31>>)
  defp dec(<< 0x14::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<32>>)
  defp dec(<< 0x3f8::10, rest::bitstring >>, length, result), do: dec(rest, length - 10, result <> <<33>>)
  defp dec(<< 0x3f9::10, rest::bitstring >>, length, result), do: dec(rest, length - 10, result <> <<34>>)
  defp dec(<< 0xffa::12, rest::bitstring >>, length, result), do: dec(rest, length - 12, result <> <<35>>)
  defp dec(<< 0x1ff9::13, rest::bitstring >>, length, result), do: dec(rest, length - 13, result <> <<36>>)
  defp dec(<< 0x15::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<37>>)
  defp dec(<< 0xf8::8, rest::bitstring >>, length, result), do: dec(rest, length - 8, result <> <<38>>)
  defp dec(<< 0x7fa::11, rest::bitstring >>, length, result), do: dec(rest, length - 11, result <> <<39>>)
  defp dec(<< 0x3fa::10, rest::bitstring >>, length, result), do: dec(rest, length - 10, result <> <<40>>)
  defp dec(<< 0x3fb::10, rest::bitstring >>, length, result), do: dec(rest, length - 10, result <> <<41>>)
  defp dec(<< 0xf9::8, rest::bitstring >>, length, result), do: dec(rest, length - 8, result <> <<42>>)
  defp dec(<< 0x7fb::11, rest::bitstring >>, length, result), do: dec(rest, length - 11, result <> <<43>>)
  defp dec(<< 0xfa::8, rest::bitstring >>, length, result), do: dec(rest, length - 8, result <> <<44>>)
  defp dec(<< 0x16::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<45>>)
  defp dec(<< 0x17::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<46>>)
  defp dec(<< 0x18::6, rest::bitstring >>, length, result), do: dec(rest, length - 6, result <> <<47>>)
  defp dec(<< 0x0::5, rest::bitstring >>, length, result), do: dec(rest, length - 5, result <> <<48>>)
end
